config/routes.rb
Rails.application.routes.draw do

  root to: redirect('simple')

  health_check_routes

  get 'simple', to: 'sets#index'
  get 'simple/*unused', to: 'sets#index'
  get 'advanced', to: 'sets#search'
  get 'advanced/*unused', to: 'sets#search'
  get 'sets/:id', to: 'sets#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include JWTCredentials

  helper_method :jwt_provided?
  helper_method :current_user
end

app/controllers/sets_controller.rb
class SetsController < ApplicationController

  before_action :materials_csv, only: [:show]

  def index
  end

  def search
  end

  def show
    respond_to do |format|
      format.csv { send_data materials_csv.build, filename: "#{filename}.csv" }
      format.tsv { send_data materials_csv.build(col_sep: "\t"), filename: "#{filename}.tsv" }
    end
  end

private

  def materials_csv
    @materials_csv ||= MaterialsCsv.new(materials_params)
  end

  def materials_params
    params.permit(:id, :sortBy, :order, :format)
  end

  def filename
    materials_csv.set.name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navlinks.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to 'Simple', simple_path, id: ("current-page-#{Rails.env.downcase}" if params[:action] == 'index') %></li>
  <li><%= link_to 'Advanced', advanced_path, id: ("current-page-#{Rails.env.downcase}" if params[:action] == 'search') %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Set Shaper | Aker</title>

    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'manifest' %>
    <%= javascript_pack_tag 'vendor' %>
  </head>

  <body>
    <%# navbar comes from aker_shared_navbar engine %>
    <%= render partial: "navbar" %>

    <div id="application"><%= yield %></div>

    <script type="text/javascript">
      var Aker = { userEmail: '<%= current_user.email %>' }
    </script>

    <%= yield :js if content_for? :js %>
    <footer style="text-align:center">
      <% if Projects::Application::VERSION.present? %>
        <%= 'Version: ' + Projects::Application::VERSION[0..6] %>
      <% end %>
    </footer>
  </body>

</html>

app/views/sets/index.html.erb
<%= content_for :js do %>
    <%= javascript_pack_tag 'set_shaper' %>
<% end %>

app/views/sets/search.html.erb
<%= content_for :js do %>
  <%= javascript_pack_tag 'search' %>
<% end %>